// Bundles the MCP App view (views/view.ts + view.css) into one self-contained HTML string, written to
// lib/generated/view.ts so the MCP server can serve it as the ui:// resource.
import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const out = await build({
  entryPoints: [path.join(root, "views/view.ts")],
  bundle: true,
  minify: true,
  format: "iife",
  target: "es2020",
  write: false,
  legalComments: "none",
});
const js = out.outputFiles[0].text.replace(/<\/script/gi, "<\\/script");
const css = await readFile(path.join(root, "views/view.css"), "utf8");
const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Lowtide</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Funnel+Display:wght@400;500&family=Funnel+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>${css}</style>
</head>
<body>
<main id="root"><p class="loading">Reading tonight's prices…</p></main>
<script>${js}</script>
</body>
</html>`;
await mkdir(path.join(root, "lib/generated"), { recursive: true });
await writeFile(
  path.join(root, "lib/generated/view.ts"),
  `// Generated by scripts/build-views.mjs. Do not edit.\nexport const VIEW_HTML = ${JSON.stringify(html)};\n`,
);
console.log(`view: ${(html.length / 1024).toFixed(0)} KB`);
